using SunnyFlamingo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SunnyFlamingo.Services.Searchers
{
    public interface IAllGoodsSearcher
    {
        Task<GoodsInformation<string>> SearchGoods(
            string producer,
            string country,
            string material,
            string color,
            decimal? priceFrom,
            decimal? priceTo,
            int from,
            int to,
            bool getQuestions);
        Task<GoodsInformation<string>> SearchComputerTechnologies(
            string producer,
            string country,
            string material,
            string color,
            decimal? priceFrom,
            decimal? priceTo,
            int from,
            int to,
            bool getQuestions);
        Task<GoodsInformation<string>> SearchLaptops(
            string producer,
            string country,
            string material,
            string color,
            string amountOfRAM,
            string CPUFrequency,
            string length,
            string height,
            string width,
            string haveFloppyDrives,
            string SSDMemory,
            string hardDiskMemory,
            string CPUSocketType,
            string computerDriveType,
            string numberOfCores,
            string floppyDrivesCount,
            string display,
            decimal? priceFrom,
            decimal? priceTo,
            int from,
            int to,
            bool getQuestions);
        Task<GoodsInformation<string>> SearchComputers(
            string producer,
            string country,
            string material,
            string color,
            string amountOfRAM,
            string CPUFrequency,
            string length,
            string height,
            string width,
            string haveFloppyDrives,
            string SSDMemory,
            string hardDiskMemory,
            string CPUSocketType,
            string computerDriveType,
            string numberOfCores,
            string floppyDrivesCount,
            decimal? priceFrom,
            decimal? priceTo,
            int from,
            int to,
            bool getQuestions);
        Task<GoodsInformation<string>> SearchFlashDrives(
            string producer,
            string country,
            string material,
            string color,
            string capacity,
            string USBSpecificationTypeValue,
            decimal? priceFrom,
            decimal? priceTo,
            int from,
            int to,
            bool getQuestions);
        Task<GoodsInformation<string>> SearchComputerParts(
            string producer,
            string country,
            string material,
            string color,
            decimal? priceFrom,
            decimal? priceTo,
            int from,
            int to,
            bool getQuestions);
        Task<GoodsInformation<string>> SearchComputerAccessories(
            string producer,
            string country,
            string material,
            string color,
            decimal? priceFrom,
            decimal? priceTo,
            int from,
            int to,
            bool getQuestions);
        Task<GoodsInformation<string>> SearchComputerDrives(
            string producer,
            string country,
            string material,
            string color,
            string capacity,
            string type,
            string formFactorType,
            decimal? priceFrom,
            decimal? priceTo,
            int from,
            int to,
            bool getQuestions);
        Task<GoodsInformation<string>> SearchCoolers(
            string producer,
            string country,
            string material,
            string color,
            string coolerType,
            string fanSizeType,
            decimal? priceFrom,
            decimal? priceTo,
            int from,
            int to,
            bool getQuestions);
        Task<GoodsInformation<string>> SearchCPUs(
            string producer,
            string country,
            string material,
            string color,
            string CPUSocketType,
            string thermalDesignPower,
            string numberOfCores,
            string numberOfThreads,
            decimal? priceFrom,
            decimal? priceTo,
            int from,
            int to,
            bool getQuestions);
        Task<GoodsInformation<string>> SearchVideoCards(
            string producer,
            string country,
            string material,
            string color,
            string driveInterface,
            string videoSize,
            string videoMemoryCapacity,
            decimal? priceFrom,
            decimal? priceTo,
            int from,
            int to,
            bool getQuestions);
        Task<GoodsInformation<string>> SearchMice(
            string producer,
            string country,
            string material,
            string color,
            string mauseType,
            string buttonsCount,
            decimal? priceFrom,
            decimal? priceTo,
            int from,
            int to,
            bool getQuestions);
        Task<GoodsInformation<string>> SearchKeyboards(
            string producer,
            string country,
            string material,
            string color,
            string keyboardType,
            decimal? priceFrom,
            decimal? priceTo,
            int from,
            int to,
            bool getQuestions);
        Task<GoodsInformation<string>> SearchHeadphones(
            string producer,
            string country,
            string material,
            string color,
            string headphonesType,
            string wirelessType,
            string connectorType,
            decimal? priceFrom,
            decimal? priceTo,
            int from,
            int to,
            bool getQuestions);
    }
}
